import { EncounterStatus } from '@prisma/client';
import { z } from "zod";

// Skema validasi untuk Anamnesis
const AnamnesisSchema = z.object({
  chiefComplaint: z.string().optional(),
  durationOfComplaint: z.string().optional(),
  locationOfComplaint: z.string().optional(),
  currentIllnessHistory: z.string().optional(),
  pastMedicalHistory: z.string().optional(),
  familyMedicalHistory: z.string().optional(),
  drugAllergyHistory: z.string().optional(),
  foodAllergyHistory: z.string().optional(),
  otherAllergyHistory: z.string().optional(),
  medicationHistory: z.string().optional(),
  currentMedications: z.string().optional(),
  surgicalHistory: z.string().optional(),
  smoking: z.boolean().optional(),
  cigarettesPerDay: z.number().int().optional(),
  alcohol: z.boolean().optional(),
  alcoholFrequency: z.string().optional(),
  exercise: z.string().optional(),
  exerciseFrequency: z.string().optional(),
  menarche: z.number().int().optional(),
  menstrualCycle: z.string().optional(),
  menstruationDuration: z.number().int().optional(),
  lastMenstrualPeriod: z.string().optional(),
  parity: z.string().optional(),
  gestationalAge: z.number().int().optional(),
  fetalMovement: z.string().optional(),
  pregnancyComplications: z.string().optional(),
  deliveryHistory: z.string().optional(),
  immunizationHistory: z.string().optional(),
  dietPattern: z.string().optional(),
  specialDiet: z.string().optional(),
  sleepPattern: z.string().optional(),
  sleepDuration: z.number().int().optional(),
  urinationPattern: z.string().optional(),
  defecationPattern: z.string().optional(),
  additionalInformation: z.string().optional(),
});

// Skema validasi untuk PhysicalExamination
const PhysicalExaminationSchema = z.object({
  bloodPressureSystolic: z.number().int().optional(),
  bloodPressureDiastolic: z.number().int().optional(),
  bodyTemperature: z.number().optional(),
  heartRate: z.number().int().optional(),
  respiratoryRate: z.number().int().optional(),
  levelOfConsciousness: z.string().optional(),
  head: z.string().optional(),
  eyes: z.string().optional(),
  ears: z.string().optional(),
  nose: z.string().optional(),
  mouth: z.string().optional(),
  throat: z.string().optional(),
  neck: z.string().optional(),
  chest: z.string().optional(),
  lungs: z.string().optional(),
  heart: z.string().optional(),
  abdomen: z.string().optional(),
  extremities: z.string().optional(),
  skin: z.string().optional(),
  neurological: z.string().optional(),
  height: z.number().optional(),
  weight: z.number().optional(),
  bodySurfaceArea: z.number().optional(),
  note: z.string().optional(),
  effectiveDateTime: z.string().datetime(),
});

const PsychologicalExaminationSchema = z.object({
  mood: z.string().optional(),
  affect: z.string().optional(),
  behavior: z.string().optional(),
  thoughtContent: z.string().optional(),
  thoughtProcess: z.string().optional(),
  perception: z.string().optional(),
  cognition: z.string().optional(),
  insight: z.string().optional(),
  judgment: z.string().optional(),
  memory: z.string().optional(),
  attention: z.string().optional(),
  concentration: z.string().optional(),
  orientation: z.string().optional(),
  speech: z.string().optional(),
  psychomotorActivity: z.string().optional(),
  suicidalIdeation: z.string().optional(),
  homicidalIdeation: z.string().optional(),
  substanceUse: z.string().optional(),
  copingMechanisms: z.string().optional(),
  socialSupport: z.string().optional(),
  stressLevel: z.string().optional(),
  sleepPattern: z.string().optional(),
  appetite: z.string().optional(),
  energyLevel: z.string().optional(),
  anxietyLevel: z.string().optional(),
  depressionScreening: z.string().optional(),
  other: z.string().optional(),
  interpretasi: z.string().optional(),
  note: z.string().optional(),
  effectiveDateTime: z.string().datetime(),
});

// Skema validasi utama untuk pembaruan encounter
export const UpdateEncounterSchema = z.object({
  status: z.nativeEnum(EncounterStatus).optional(),
  endDate: z.string().datetime().optional(),
  diagnosis: z.string().optional(),
  treatmentPlan: z.string().optional(),
  notes: z.string().optional(),
  anamnesis: AnamnesisSchema.optional(),
  physicalExamination: PhysicalExaminationSchema.optional(),
  psychologicalExamination: PsychologicalExaminationSchema.optional(),
});